# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker" # See documentation for possible values
    # Look for a `Dockerfile` in the `root` directory
    directory: "/" # Location of package manifests
    # Check for updates once a week
    schedule:
      interval: "weekly"
	labels:
	  - "docker-dependencies"
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    # Look for a `Dockerfile` in the `root` directory
    directory: "/dependencies/console-client/" # Location of package manifests
    # Check for updates once a week
    schedule:
      interval: "daily"
	labels:
	  - "docker-dependencies"